project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
      - about.qmd
      - movie.qmd
      - Reflection.qmd

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



