project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: movie.qmd
        text: Movies
      - href: Reflection.qmd
        text: Reflections

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left